[workspace]
name = "orinoco-lite-engineering"
channels = ["conda-forge"]
platforms = [{ platform = "osx-arm64", macos = "14.0" }, "linux-64"]

[dependencies]
python = ">=3.12,<3.13"
git = ">=2.55.0,<3"
hugo = "==0.154.5"
nodejs = ">=22,<23"
make = "==4.4.1"

[target.linux-64.dependencies]
git-annex = "==10.20260601"

[target.osx-arm64-macos-14-0.pypi-dependencies]
git-annex = "==10.20260601"

[pypi-dependencies]
orinoco-lite = { path = ".", editable = true }
build = "==1.6.0"
snapper-fmt = "==0.10.0"
pre-commit = "==4.3.0"
pytest = ">=9,<10"
datalad = "==1.6.2"
click-option-group = ">=0.5, <0.6"
copier = "==9.10.3"

[tasks]
records-jsonl-to-yaml = "datalad run --explicit --input sourcedata/downloaded/records.jsonl --output site-specific/metadata orinoco-lite dev records jsonl-to-yaml"
records-get = "datalad run --explicit --output sourcedata/downloaded/records.jsonl --output sourcedata/downloaded/records.jsonl.manifest.json orinoco-lite dev records get"
build-package = "python -m build --outdir build/package"
setup-upstream = "bash tools/setup-upstream.sh"
install-hooks = "git config core.hooksPath .githooks"
